name: Jest test workflow for linear search algo

on:
  push:

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu:latest

    steps:
    - name: Clone repo
      uses: actions/checkout/@v4

    - name: Build docker img
      run: docker build -t jest-test . 

    - name: build docker img
      run: docker run --rm jest-test 